title: Blaise Cruz
description: Low-resource natural language processing, multilinguality, and language technology.
url: "https://blaisecruz.com"
baseurl: ""
markdown: kramdown

collections:
  news:
    output: false
  explainers:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
